@host=127.0.0.1
@port={{$dotenv PORT}}
@base=http://{{host}}:{{port}}
@json=application/json

### test baseurl
GET {{base}}

### send login request
# @name login
POST {{base}}/login
Content-Type: {{json}}

{
  "email": "anik@test.com",
  "password": "password123"
}


### send signup request
# @name signup
POST {{base}}/register
Content-Type: {{json}}

{
  "name": "Anik Mohammad",
  "email": "anik3@test.com",
  "password": "password123"
}

### fetch all posts
GET {{base}}/posts

### fetch one post
@postId=5
GET {{base}}/posts/{{postId}}

### create a new post
POST {{base}}/posts
Content-Type: {{json}}
# Authorization: Bearer {{login.response.body.token}}

{
  "title": "post 5",
  "content": "post content"
}

### update post
PATCH {{base}}/posts/{{postId}}
Content-Type: {{json}}
# Authorization: Bearer {{login.response.body.token}}

{
  "title": "updated post title!"
  //"content": "post content updated again",
  //"published": false
}

### delete a post
DELETE {{base}}/posts/{{postId}}
# Authorization: Bearer {{login.response.body.token}}
