@host=127.0.0.1
@port={{$dotenv PORT}}
@base=http://{{host}}:{{port}}
@json=application/json

### test baseurl
GET {{base}}

### send login request
# @name login
POST {{base}}/login
Content-Type: {{json}}

{
  "email": "anik@test.com",
  "password": "password123"
}


### send signup request
# @name signup
POST {{base}}/register
Content-Type: {{json}}

{
  "name": "Anik Mohammad",
  "email": "anik@test.com",
  "password": "password123"
}

### fetch all posts
GET {{base}}/posts

### fetch one post
@postId=1
GET {{base}}/posts/{{postId}}
